relay-reactjs-chat/package.json, store-reactjs-chat/package.json, web-chat/package.json
So two examples can be started at the same time to test things faster.
=> chore: set different ports for React projects

light-js/index.html, relay-angular-chat/src/app/messages/messages.component.ts, relay-js/index.html, relay-reactjs-chat/src/App.js
All examples do not connect to the same fleet at the moment so the gain is limited.
=> feat: use same content topics across examples when possible

eth-pm/craco.config.js, eth-pm/package.json, eth-pm/pnpm-lock.yaml, eth-pm/src/App.tsx, eth-pm/src/BroadcastPublicKey.tsx, eth-pm/src/messaging/Messaging.tsx, eth-pm/src/messaging/SendMessage.tsx, eth-pm/src/waku.ts
This PR addresses https://github.com/waku-org/js-waku-examples/issues/88:
- switch the example from using light node with `filter` and `store` to now using `relay`
- setup craco as the bundler
TODO/confirm:
=> refactor: change eth-pm using lightnode, filter to now use relay

relay-js/index.html
Was going through this example today and noticed the links did not work, I found what I believe to be the correct links on the new docs site
=> Update links pointing to old wakuconnect docs

ci/Jenkinsfile
Since prev PR didn't fix the issue 
https://github.com/waku-org/js-waku-examples/pull/178
=> Fix Jenkins CI by escaping brackets 

ci/Jenkinsfile
Not sure why this massive construction was added:
https://github.com/waku-org/js-waku-examples/blob/622aecb422f925feefee65b3bd0d0014bd439342/ci/Jenkinsfile#L86-L120
When we can just `cp` stuff:
https://github.com/waku-org/js-waku-examples/blob/012ef6089b399a35df5d8305bec29e6880ae34fa/ci/Jenkinsfile#L83
=> ci: simplify overcomplicated file copying

examples/web-chat/.cspell.json, examples/web-chat/package-lock.json, examples/web-chat/package.json, examples/web-chat/src/App.tsx, examples/web-chat/src/types/types.d.ts
Uses DNS Discovery to find nodes instead of providing a predefined list of nodes
Declares a module for `@waku/dns-discovery` (ref: https://github.com/waku-org/js-waku/issues/1124) -- will be followed up by another PR -- tracking here: https://github.com/waku-org/js-waku-examples/issues/191
=> feat: use dns-discovery instead of predefined list

.gitignore, ci/Jenkinsfile, examples/noise-js/webpack.config.js
`noise-js` example should be built and published by our CI
The issue with it breaking pipeline was in wrong name of a folder with build artifact - now it is fixed.
```
+ cp -r build/. /home/jenkins/workspace/website/examples.waku.org/build/docs/noise-js
cp: can't stat 'build/.': No such file or directory
```
=> fix: publishing issue of noise-js example

.github/workflows/ci.yml
I think it is safe enough to make publishing with `latest` tag by default.
=> chore: make latest as default tag for @waku/create-app

examples/noise-js/index.html
Shows small message in bottom part of the page.
relevant to https://github.com/waku-org/js-waku/issues/950
=> chore: add notice about go-waku interop

examples/web-chat/src/MessageInput.tsx, examples/web-chat/src/Room.tsx, examples/web-chat/src/hooks.ts
Because in some cases node connection fails to one of peers, libp2p does not invoke `change:protocols` event which was trigger to populate peers list. 
Populate peers without waiting for the event. 
PR also adds `try/catch` and prevent sending messages if not allowed due to lack of `lightPush` peers or other conditions.
Partially resolves one of the comments from follow-ups to `@waku/react` - https://github.com/waku-org/js-waku/issues/1060#issuecomment-1447280851
=> fix: populate peers without waiting for an event

README.md
I was looking at some examples and realized the links in README are broken.
=> chore: fix code links in the README

examples/noise-js/index.js, examples/noise-js/package-lock.json, examples/noise-js/package.json, examples/noise-rtc/index.js, examples/noise-rtc/package-lock.json, examples/noise-rtc/package.json
~~Blocked by https://github.com/waku-org/js-waku/pull/1357~~
Waiting for `@waku/core@0.0.18` to be released.
=> chore: use filter as IReceiver for noise

examples/light-js/index.html, examples/noise-js/index.js, examples/noise-js/package-lock.json, examples/noise-js/package.json, examples/noise-rtc/index.js, examples/noise-rtc/package-lock.json, examples/noise-rtc/package.json, examples/relay-js/index.html, examples/rln-js/index.js
Migrate main and simple JS examples to use `@waku/sdk`. 
Next steps:
- migrate more complex examples one by one;
- check if there are no regressions in the new release;
Resolves the last part of https://github.com/waku-org/js-waku/issues/1353
=> feat: use @waku/sdk

examples/eth-pm/README.md, examples/relay-angular-chat/README.md, examples/relay-reactjs-chat/README.md, examples/rln-js/README.md, examples/store-reactjs-chat/README.md, examples/web-chat/README.md
Updated paths for quick copy and use instructions in README for some of the examples. 
Commands listed don't work if someone tries to use just by copy pasting them, since the paths for cd are not relative to previous command.
=> chore: update paths in quick use instructions in README

examples/light-js/index.html
In this PR I introduce the usage of DnsDiscovery to fetch one peer. 
I deliberately use DnsDiscovery directly without `defaultPeers` to showcase direct usage and keep input as a way to set a node. 
cc: @fryorcraken @danisharora099
=> feat(light-js): add discovery of a peer

examples/web-chat/src/ChatList.tsx, examples/web-chat/src/Message.ts, examples/web-chat/src/hooks.ts, examples/web-chat/src/ordered_array.ts, examples/web-chat/src/types.ts
Also:
- remove messages that have a timestamp further than tomorrow.
- remove dupes
=> fix: ensure messages are always ordered

examples/web-chat/src/App.tsx
Strange thing happened and @vpavlin while sending `base64` messages through `rpc` to his `nwaku` node put such a message into Store that while web-chat example tries to fetch them hangs and tab crashed. 
As mitigation right now - setting limit to last 30 minutes.
Will look into it later.
=> fix: mitigate hanging of web-chat

examples/web-chat/.cspell.json
Not sure if I escaped backslash properly.
Please test.
See:
- https://github.com/waku-org/js-waku-examples/pull/190/files#r1080774184
- https://discord.com/channels/1110799176264056863/1111541029309534249/1158771714868658196
=> fix: change enrtree public key to pattern

README.md
`rln-js` has been removed recently from this repo.
=> chore: remove details about removed example
